---
title: "PCA"
author: "Hang Zhang"
date: "11/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 1
```{r}
library(readr)
library(tidyverse)
library(factoextra)
library(skimr)
library(corrplot)
library(dplyr)
library(purrr)
library(cluster)

data <- read_csv("application_train.csv")

PCA_clean <- data %>% select(-SK_ID_CURR,-TARGET)
summary(PCA_clean)
```
## 2
```{r}
PCA_c <- cor(PCA_clean)
corrplot(PCA_c,
         method = "color",
         type="upper",
         diag=F,
         addCoef.col = "black")

PCA_p <- prcomp(PCA_clean,center = T, scale = T)

fviz_screeplot(PCA_p,addlabels=T,ylim=c(0,100))
get_eigenvalue(PCA_p)

fviz_contrib(PCA_p,choice = "var",axes = 1:14)
fviz_pca_ind(PCA_p,repl=T,
             gradient.cols=c("#00AFBB","#E7B800","#FC4E07"),
             col.ind = "cos2")
```
```{r}
stock_pcs=predict(stock_p,newdata=stock_clean)
stock_pcs=as.data.frame(stock_pcs)
stock_pcs <- stock_pcs[,1:14]

```

### cluster
```{r}
# Use the WSS method
x=1:25
stock_wss = function(k) {
  km = kmeans(stock_pcs, k, nstart=25, iter=25)
  kwss = km$tot.withinss
  return(kwss)
}

wss_stock=map_dbl(x,stock_wss)
plot(x,wss_stock,type="b", main = "Judges Select k - WSS for Stock")
# Silhoutte evaluation
fviz_nbclust(stock_pcs,kmeans, method = "silhouette",k.max = 20)
# cluster
stock_k = kmeans(stock_pcs,centers = 3,iter.max = 25,nstart = 25)
plot(silhouette(stock_k$cluster,dist = dist(stock_z)),col=1:3)
fviz_cluster(stock_k,data = stock_clean)
```

